/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.questionnaire;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.questionnaire.guice.QuestionnaireModule;
import com.questionnaire.resource.QuestionnaireResource;
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;

public class QuestionnaireApp extends Application<Configuration> {

    public static void main(String[] args) {
        try {
            new QuestionnaireApp().run(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public void run(Configuration configuration, Environment environment) throws Exception {
        Injector injector = Guice.createInjector(new QuestionnaireModule());
        environment.jersey().register(injector.getInstance(QuestionnaireResource.class));
    }
}
