/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.questionnaire;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.questionnaire.dao.MySqlQuestionnaireDao;
import com.questionnaire.guice.QuestionnaireModule;
import com.questionnaire.model.Answer;
import com.questionnaire.model.QASession;
import com.questionnaire.model.Question;
import org.junit.Ignore;
import org.junit.Test;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.Assert.assertEquals;

@Ignore
//Required mysql up and running thus ignored
public class QuestionnaireDatabaseTest {

  Injector injector = Guice.createInjector(new QuestionnaireModule());
  MySqlQuestionnaireDao dao = injector.getInstance(MySqlQuestionnaireDao.class);

  @Test
  public void testDatabase() {

    QASession qaSession = new QASession(1L, LocalDateTime.now(), LocalDateTime.now(), "user1");
    dao.saveQASession(qaSession);

    QASession dbQASession = dao.getQASession(1L);
    assertEquals(dbQASession.getQaId().longValue(), 1L);
    assertEquals(dbQASession.getHostName(), "user1");

    Question question = new Question(1L, "what is the day today?", "user2", 1L);
    dao.saveQuestion(question);

    Answer answer = new Answer(1L, "saturday", "http://www.imageswallpaper.in/wp-content/uploads/2017/04/Saturday-Image-4.jpg", "user3");
    dao.saveAnswer(answer);

    List<Question> questions = dao.getQuestions(1L, null);
    assertEquals(questions.size(), 1);
    questions = dao.getQuestions(1L, true);
    assertEquals(questions.size(), 1);
    questions = dao.getQuestions(1L, false);
    assertEquals(questions.size(), 0);

    cleanUp();
  }

  private void cleanUp() {
    DataSource dataSource = injector.getInstance(DataSource.class);
    try (Connection connection = dataSource.getConnection();
         PreparedStatement ps = connection.prepareStatement("DROP DATABASE IF EXISTS questionnaire")) {
      ps.execute();
    } catch (SQLException e) {
      throw new RuntimeException(e);
    }
  }
}
